/// app-screen
export const APP_HOME_SCREEN = 'APP_HOME_SCREEN';
export const APP_STUDENT_SCREEN = 'APP_STUDENT_SCREEN';
export const APP_LECTURER_SCREEN = 'APP_LECTURER_SCREEN';

/// student-screen
export const STUDENT_HOME_SCREEN = 'STUDENT_HOME_SCREEN';
export const STUDENT_SIMPLIFYING_FRACTION = 'STUDENT_SIMPLIFYING_FRACTION';
export const STUDENT_ENDING_SCREEN = 'STUDENT_ENDING_SCREEN';

// simplifying-screen
export const SIMPLIFYING_HOME_SCREEN = 'SIMPLIFYING_HOME_SCREEN';
export const SIMPLIFYING_EXAM_SCREEN = 'SIMPLIFYING_EXAM_SCREEN';