/// app-screen
export const APP_HOME_SCREEN = 'APP_HOME_SCREEN';
export const APP_STUDENT_SCREEN = 'APP_STUDENT_SCREEN';
export const APP_LECTURER_SCREEN = 'APP_LECTURER_SCREEN';

/// student-screen
export const STUDENT_HOME_SCREEN = 'STUDENT_HOME_SCREEN';
export const STUDENT_SIMPLIFYING_FRACTION = 'STUDENT_SIMPLIFYING_FRACTION';
export const STUDENT_ENDING_SCREEN = 'STUDENT_ENDING_SCREEN';
export const STUDENT_WHEN_TO_SIMPLIFY = 'STUDENT_WHEN_TO_SIMPLIFY';
export const STUDENT_STEP_BY_STEP = 'STUDENT_STEP_BY_STEP';

// simplifying-screen
export const SIMPLIFYING_HOME_SCREEN = 'SIMPLIFYING_HOME_SCREEN';
export const SIMPLIFYING_EXAM_SCREEN = 'SIMPLIFYING_EXAM_SCREEN';
export const SIMPLIFYING_MODIFY_QUESTION = 'SIMPLIFYING_MODIFY_QUESTION';

// when-to-simplify-screen
export const WHEN_TO_SIMPLIFY_HOME = 'WHEN_TO_SIMPLIFY_HOME';
export const WHEN_TO_SIMPLIFY_EXAM = 'WHEN_TO_SIMPLIFY_EXAM';
export const WHEN_TO_SIMPLIFY_MODIFY_QUESTION = 'WHEN_TO_SIMPLIFY_MODIFY_QUESTION';

///step-by-step-screen
export const STEP_BY_STEP_HOME = 'STEP_BY_STEP_HOME';
export const STEP_BY_STEP_EXAM = 'STEP_BY_STEP_EXAM';

///lecturer-screen
export const LECTURER_SIMPLIFY = 'LECTURER_SIMPLIFY';
export const LECTURER_WHEN_TO_SIMPLIFY = 'LECTURER_WHEN_TO_SIMPLIFY';